## Assembles the MetaVidence R package from the app.R at the repository root.
##
## That app.R is the ONE source of truth. Three artefacts derive from it:
##   build_shinylive.R -> docs/    (the WebAssembly website)
##   build_package.R   -> pkg/     (the R package, for CRAN)
##   shiny::runApp()   -> the root (development)
## Copying by hand would be exactly how the three drift apart in silence.

pkg_dir <- "pkg"
app_dir <- file.path(pkg_dir, "inst", "app")
fontes <- c("app.R", "easymeta.css", "easymeta.js")

dir.create(app_dir, recursive = TRUE, showWarnings = FALSE)
for (f in fontes) {
  if (!file.exists(f)) stop("Missing source file: ", f)
  file.copy(f, file.path(app_dir, f), overwrite = TRUE)
}
cat("sources synced to", app_dir, "\n")

## app.R must not be read as package code: it is an application, evaluated at
## run time. It lives in inst/, which R does not interpret. That is also why
## R/run_app.R carries an @importFrom for each dependency: R CMD check never
## reads inst/, so without them every Import would look declared and unused.
writeLines(c(
  "^.*\\.Rproj$", "^\\.Rproj\\.user$", "^\\.github$",
  "^docs$", "^shinylive_app$", "^design$", "^tutorials$",
  "^build_.*\\.R$", "^loading_screen\\.html$", "^DEPLOY\\.md$",
  "^app\\.R$", "^easymeta\\.(css|js)$", "^batch_fixture\\.xlsx$",
  "^app.*\\.bak[0-9]*$", "^image\\.jpeg$", "^cran-comments\\.md$"
), file.path(pkg_dir, ".Rbuildignore"))

## The CRAN notes travel with the package, because devtools::submit_cran looks
## for them inside it, but they stay OUT of the tarball via the line above.
if (file.exists("cran-comments.md")) {
  file.copy("cran-comments.md", file.path(pkg_dir, "cran-comments.md"), overwrite = TRUE)
}

## ---- inst/CITATION ------------------------------------------------------
## Generated from METAVIDENCE_CITATION in app.R, the single source of truth.
## This is what citation("metavidence") reads once the package is installed.
fonte <- new.env()
exprs <- parse("app.R")
for (i in seq_len(length(exprs) - 1)) {
  tryCatch(eval(exprs[[i]], envir = fonte), error = function(e) invisible(NULL))
}
cit <- fonte$METAVIDENCE_CITATION
if (is.null(cit)) stop("METAVIDENCE_CITATION was not found in app.R")

entradas <- character(0)
if (!is.null(cit$paper)) {
  p <- cit$paper
  entradas <- c(entradas, sprintf(
    'bibentry(
  bibtype  = "Article",
  title    = "%s",
  author   = %s,
  journal  = "%s",
  year     = "%d",
%s  header   = "To cite MetaVidence in publications, please use:"
)',
    p$title, p$r_author, p$journal, p$year,
    if (!is.null(p$doi) && nzchar(p$doi)) sprintf('  doi      = "%s",
', p$doi) else ""))
}
s <- cit$software
entradas <- c(entradas, sprintf(
  'bibentry(
  bibtype  = "Manual",
  title    = "%s",
  author   = person(given = c(%s), family = "%s", comment = c(ORCID = "%s")),
  year     = "%d",
  note     = "R package version %s",
  url      = "%s",
  header   = "%s",
  footer   = "%s"
)',
  s$title, paste(sprintf('"%s"', s$given), collapse = ", "), s$family, s$orcid,
  s$year, s$version, s$url,
  if (is.null(cit$paper)) "To cite MetaVidence in publications, please use:"
  else "And, to credit the version you ran:",
  ## An installed package can only show the citation that shipped with it. If
  ## the paper appears after this release, this line is what sends the reader
  ## to the current wording without the app having to fetch anything.
  paste0("The current citation is always at ", cit$cite_page)))

## A binary connection, not writeLines() straight to the path: on Windows the
## default connection writes CRLF, and this file ships inside the CRAN tarball.
## Everything else in the package is pinned to LF by .gitattributes, so this
## would be the one file whose line endings depended on who built it.
con <- file(file.path(pkg_dir, "inst", "CITATION"), open = "wb")
writeLines(c(
  "## Generated by build_package.R from METAVIDENCE_CITATION, in app.R.",
  "## Do not edit here: the edit would be lost on the next package build.",
  "",
  entradas
), con, sep = "
")
close(con)
cat("inst/CITATION generated
")

## roxygen2 generates NAMESPACE and man/ from the comments in R/
if (requireNamespace("roxygen2", quietly = TRUE)) {
  roxygen2::roxygenise(pkg_dir, clean = TRUE)
  cat("documentation generated\n")
} else {
  cat("WARNING: roxygen2 not installed, NAMESPACE and man/ were not updated\n")
}

## ---- verification --------------------------------------------------------
cat("\npost-build checks\n")
esperados <- c("DESCRIPTION", "NAMESPACE", "R/run_app.R", "inst/CITATION",
               "inst/app/app.R", "inst/app/easymeta.css", "inst/app/easymeta.js")
for (f in esperados) {
  cat(sprintf("  %-26s %s\n", f,
              if (file.exists(file.path(pkg_dir, f))) "ok" else "MISSING"))
}

## the package's copy of the app has to be identical to the one at the root
iguais <- vapply(fontes, function(f) {
  identical(readLines(f, warn = FALSE), readLines(file.path(app_dir, f), warn = FALSE))
}, logical(1))
cat(sprintf("  %-26s %s\n", "in sync with the root",
            if (all(iguais)) "ok" else paste("DIVERGED:", paste(fontes[!iguais], collapse = ", "))))

tam <- sum(file.info(list.files(pkg_dir, recursive = TRUE, full.names = TRUE))$size)
cat(sprintf("  %-26s %.2f MB (CRAN limit: 5 MB)\n", "size", tam / 1024^2))
